In [22]:
# Imports and pip installations (if needed)
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import classification_report

# Part 1: Load the dataset

In [23]:
# Load the dataset (load remotely or locally)
df = pd.read_csv("iris.csv")

# Output the first 15 rows of the data
print(df.head(15))

# Display a summary of the table information (number of datapoints, etc.)
print(df.info())
print(df.describe())


    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8         

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

The Iris dataset is a classic dataset used for classification tasks in machine learning. It contains 150 observations of three different species of Iris flowers. Each flower is described by four features: Sepal Length (cm), Sepal Width (cm), Petal Length (cm), Petal Width (cm). Our label Y is the species of flower which is our target variable. In the dataset, the target column contains labels representing the three Iris species: 0: Iris Setosa, 1: Iris Versicolor and 2: Iris Virginica.


# Part 2: Split the dataset into train and test

In [24]:
# Take the dataset and split it into our features (X) and label (y)
X = df.drop(columns=['species'])  # 'species' is the target label
y = df['species']

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)


# Part 3: Logistic Regression

In [25]:
# i. Use sklearn to train a LogisticRegression model on the training set
log_reg = LogisticRegression(max_iter=200)
log_reg.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
sample_datapoint = [X_test.iloc[5]]
probabilities = log_reg.predict_proba(sample_datapoint)
print(f"Predicted probabilities for each class: {probabilities}")
print(f"Actual label for the sample datapoint: {y_test.iloc[5]}")

# iii. Report on the score for Logistic regression model, what does the score measure?
score = log_reg.score(X_test, y_test)
print(f"Logistic Regression Model Score: {score}")

# iv. Extract the coefficents and intercepts for the boundary line(s)
coefficients = log_reg.coef_
intercepts = log_reg.intercept_
print(f"Coefficients (for each class):\n{coefficients}")
print(f"Intercepts (for each class): {intercepts}")

Predicted probabilities for each class: [[9.59980571e-01 4.00193334e-02 9.52413881e-08]]
Actual label for the sample datapoint: setosa
Logistic Regression Model Score: 1.0
Coefficients (for each class):
[[-0.42616255  0.96868276 -2.44813807 -1.03770245]
 [ 0.51152508 -0.21829295 -0.21575907 -0.84253612]
 [-0.08536253 -0.7503898   2.66389714  1.88023857]]
Intercepts (for each class): [  9.52956426   1.89758309 -11.42714735]


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


The score measures the accuracy of the model, which is the proportion of correct predictions out of all predictions made.

# Part 4: Support Vector Machine

In [26]:
# i. Use sklearn to train a Support Vector Classifier on the training set
svc = SVC(probability=True)
svc.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
sample_datapoint = [X_test.iloc[5]]
probabilities = svc.predict_proba(sample_datapoint)
print(f"Predicted probabilities for each class: {probabilities}")
print(f"Actual label for the sample datapoint: {y_test.iloc[5]}")

# iii. Report on the score for the SVM, what does the score measure?
score = svc.score(X_test, y_test)
print(f"SVM Model Score: {score}")

Predicted probabilities for each class: [[0.95840673 0.02979056 0.01180271]]
Actual label for the sample datapoint: setosa
SVM Model Score: 1.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


# Part 5: Neural Network

In [27]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
mlp = MLPClassifier(max_iter=300, random_state=42)
mlp.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
sample_datapoint = [X_test.iloc[5]]
probabilities = mlp.predict_proba(sample_datapoint)
print(f"Predicted probabilities for each class: {probabilities}")
print(f"Actual label for the sample datapoint: {y_test.iloc[5]}")

# iii. Report on the score for the Neural Network, what does the score measure?
score = mlp.score(X_test, y_test)
print(f"Neural Network Model Score: {score}")

# iv: Experiment with different options for the neural network, report on your best configuration
my_mlp = MLPClassifier(hidden_layer_sizes=(50, 30), activation='relu', solver='adam',learning_rate='adaptive', max_iter=500, random_state=42)
my_mlp.fit(X_train, y_train)
score_best = my_mlp.score(X_test, y_test)
print(f"My Neural Network Model Score: {score_best}")

Predicted probabilities for each class: [[9.77953998e-01 2.20454752e-02 5.26980335e-07]]
Actual label for the sample datapoint: setosa
Neural Network Model Score: 1.0
My Neural Network Model Score: 1.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


# Part 6: K-Nearest Neighbors

In [28]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
sample_datapoint = [X_test.iloc[5]]
probabilities = knn.predict_proba(sample_datapoint)
print(f"Predicted probabilities for each class: {probabilities}")
print(f"Actual label for the sample datapoint: {y_test.iloc[5]}")

# iii. Report on the score for kNN, what does the score measure?
score = knn.score(X_test, y_test)
print(f"kNN Model Score: {score}")

Predicted probabilities for each class: [[1. 0. 0.]]
Actual label for the sample datapoint: setosa
kNN Model Score: 1.0


/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

As we can see above, the model that performed best was k Nearest Neighbours. The order from best to worst goes k Nearest Neighbours, Neural Networks, Logistic Regression and SVM. \
\
The kNN model performed the best, which is somewhat expected for a dataset like Iris because:\
The Iris dataset is small, well-clustered, and non-complex, making it ideal for a proximity-based model like kNN.\
kNN performs well when data points from the same class are close together, which is true for Iris, especially for species like Setosa.\
kNN, by nature, doesn’t create an explicit model; it classifies based on neighbors, which may have allowed it to generalize better on this dataset.\
\
Here is what surprised me about the results:\
SVM’s Underperformance: SVM typically does well with small datasets, so its poor performance could indicate poor parameter tuning or that it was unnecessarily complex for this task.\
Neural Network’s Limitations: Despite its power, the neural network's performance was limited, highlighting how important it is to match the model to the dataset size and complexity.