In [12]:
# Imports and pip installations (if needed)
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, accuracy_score


# Part 1: Load the dataset

In [13]:
# Load the dataset (load remotely or locally)
data = pd.read_csv("iris.csv")
# Output the first 15 rows of the data
print("First 15 rows of the Iris dataset:")
print(data.head(15))
# Display a summary of the table information (number of datapoints, etc.)
print("\nDataset Information:")
print(data.info())

print("\nClass distribution:")
print(data['species'].value_counts())


First 15 rows of the Iris dataset:
    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

The Iris dataset is a classic dataset in machine learning that includes measurements of three species of iris flowers: Setosa, Versicolor, and Virginica. Each flower is described by four features: sepal length, sepal width, petal length, and petal width, all measured in centimeters. These measurements serve as input features to help distinguish between the species. The species labels (Setosa, Versicolor, Virginica) are the target variable, with 50 samples for each species, making the dataset balanced and well-suited for classification tasks. This dataset enables us to predict the species of an iris flower based on its physical dimensions.

# Part 2: Split the dataset into train and test

In [14]:
# Take the dataset and split it into our features (X) and label (y)

X = data.drop(columns=['species']) 
y = data['species']  

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42, stratify=y)

print("Training set size:", X_train.shape[0])
print("Test set size:", X_test.shape[0])

Training set size: 135
Test set size: 15


# Part 3: Logistic Regression

In [15]:
# i. Use sklearn to train a LogisticRegression model on the training set
log_reg = LogisticRegression(max_iter=200)
log_reg.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample = X_test.iloc[0] 
probabilities = log_reg.predict_proba([sample])

print("Predicted probabilities for each class for the sample datapoint:")
print(probabilities)
# iii. Report on the score for Logistic regression model, what does the score measure?
score = log_reg.score(X_test, y_test)
print("\nLogistic Regression model score:", score)
# iv. Extract the coefficents and intercepts for the boundary line(s)
coefficients = log_reg.coef_
intercepts = log_reg.intercept_

print("\nCoefficients of the Logistic Regression model:")
print(coefficients)
print("\nIntercepts of the Logistic Regression model:")
print(intercepts)

Predicted probabilities for each class for the sample datapoint:
[[0.00305726 0.87719395 0.11974879]]

Logistic Regression model score: 0.9333333333333333

Coefficients of the Logistic Regression model:
[[-0.42038361  0.92070254 -2.43776535 -1.0642716 ]
 [ 0.42961816 -0.33500382 -0.10458834 -0.96424244]
 [-0.00923455 -0.58569872  2.54235369  2.02851404]]

Intercepts of the Logistic Regression model:
[  9.59273941   2.42083309 -12.0135725 ]


/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


# Part 4: Support Vector Machine

In [16]:
# i. Use sklearn to train a Support Vector Classifier on the training set
svm = SVC(probability=True)  
svm.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample = X_test.iloc[0]  # Selecting the first datapoint in the test set
probabilities = svm.predict_proba([sample])

print("Predicted probabilities for each class for the sample datapoint:")
print(probabilities)
# iii. Report on the score for the SVM, what does the score measure?
score = svm.score(X_test, y_test)
print("\nSVM model score:", score)

Predicted probabilities for each class for the sample datapoint:
[[0.00734348 0.93380941 0.05884711]]

SVM model score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


# Part 5: Neural Network

In [17]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
mlp = MLPClassifier(hidden_layer_sizes=(10,), max_iter=500, random_state=42)
mlp.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample = X_test.iloc[0] 
probabilities = mlp.predict_proba([sample])
print("Predicted probabilities for each class for the sample datapoint:")
print(probabilities)
# iii. Report on the score for the Neural Network, what does the score measure?
score = mlp.score(X_test, y_test)
print("\nNeural Network model score:", score)
# iv: Experiment with different options for the neural network, report on your best configuration
best_score = 0
best_config = None

for config in [(5,), (10,), (10, 10), (20, 20)]:
    mlp_test = MLPClassifier(hidden_layer_sizes=config, max_iter=500, random_state=42)
    mlp_test.fit(X_train, y_train)
    test_score = mlp_test.score(X_test, y_test)
    
    print(f"Configuration: {config}, Score: {test_score}")
    
    if test_score > best_score:
        best_score = test_score
        best_config = config

print(f"\nBest configuration: {best_config} with score: {best_score}")

/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Predicted probabilities for each class for the sample datapoint:
[[0.05340988 0.50750443 0.43908569]]

Neural Network model score: 0.9333333333333333
Configuration: (5,), Score: 0.7333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Configuration: (10,), Score: 0.9333333333333333
Configuration: (10, 10), Score: 1.0
Configuration: (20, 20), Score: 1.0

Best configuration: (10, 10) with score: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


# Part 6: K-Nearest Neighbors

In [18]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
knn = KNeighborsClassifier(n_neighbors=3) 
knn.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample = X_test.iloc[0]  
probabilities = knn.predict_proba([sample])

print("Predicted probabilities for each class for the sample datapoint:")
print(probabilities)
# iii. Report on the score for kNN, what does the score measure?
score = knn.score(X_test, y_test)
print("\nKNN model score:", score)

Predicted probabilities for each class for the sample datapoint:
[[0. 1. 0.]]

KNN model score: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

The results show that simpler models like Logistic Regression and SVM performed best on the Iris dataset, achieving high accuracy due to the dataset's linear separability. Neural Networks also performed well but required more tuning, while KNN was effective but sensitive to the choice of n_neighbors. Surprisingly, the simplicity of Logistic Regression and SVM proved sufficient for this task, highlighting that complex models aren’t always necessary for linearly separable data. This exercise emphasizes the importance of choosing models based on dataset characteristics rather than complexity alone.