In [1]:
# Imports and pip installations (if needed)
import numpy as np
import pandas as pd

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.neural_network import MLPClassifier

# Part 1: Load the dataset

In [2]:
# Load the dataset (load remotely or locally)
df = pd.read_csv('iris.csv')
# Output the first 15 rows of the data
print(df.head(15))
# Display a summary of the table information (number of datapoints, etc.)
print(df.info())

    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  setosa
14           5.8         

## About the dataset
The dataset contains 150 entries and 5 columns. The first four columns represent the attributes of the Iris flowers (these are the features): sepal_length, sepal_width, petal_length, petal_width. The label is the 5th column, species. The species column contains the following three classes of Iris flowers: setosa, versicolor, and virginica. The goal of the classification task is to predict the species of the flower (label) based on its features (measurements).

# Part 2: Split the dataset into train and test

In [3]:
# Take the dataset and split it into our features (X) and label (y)
X = df.drop('species', axis=1)  
y = df['species']
# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)
#Displaying the shape of the resulting dataset
print("Training feature set shape:", X_train.shape)
print("Test feature set shape:", X_test.shape)
print("Training label set shape:", y_train.shape)
print("Test label set shape:", y_test.shape)

Training feature set shape: (135, 4)
Test feature set shape: (15, 4)
Training label set shape: (135,)
Test label set shape: (15,)


# Part 3: Logistic Regression

In [4]:
# i. Use sklearn to train a LogisticRegression model on the training set
logistic_model = LogisticRegression(max_iter=200) 
logistic_model.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample_data_point = X_test.iloc[[0]] 
predicted_probabilities = logistic_model.predict_proba(sample_data_point)
print("Predicted probabilities for each class:", predicted_probabilities)
# iii. Report on the score for Logistic regression model, what does the score measure?
y_pred = logistic_model.predict(X_test)  
score = accuracy_score(y_test, y_pred)    
print("Accuracy score of the Logistic Regression model:", score)
print("The accuracy score measures the proportion of correctly classified samples in the test set.")
# iv. Extract the coefficents and intercepts for the boundary line(s)
coefficients = logistic_model.coef_         
intercepts = logistic_model.intercept_       
print("Coefficients for each class:\n", coefficients)
print("Intercepts for each class:\n", intercepts)

Predicted probabilities for each class: [[0.0034491  0.83683574 0.15971516]]
Accuracy score of the Logistic Regression model: 1.0
The accuracy score measures the proportion of correctly classified samples in the test set.
Coefficients for each class:
 [[-0.42830334  0.96729205 -2.44742526 -1.03780396]
 [ 0.5130202  -0.22029888 -0.21604909 -0.84453741]
 [-0.08471686 -0.74699317  2.66347435  1.88234137]]
Intercepts for each class:
 [  9.54356486   1.89887279 -11.44243765]


In this case, the accuracy score is 1. This means all the samples in the test set were classified correctly!

# Part 4: Support Vector Machine

In [5]:
# i. Use sklearn to train a Support Vector Classifier on the training set
svm_model = SVC(probability=True, random_state=42)
svm_model.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample_data_point = X_test.iloc[[0]] 
predicted_probabilities = svm_model.predict_proba(sample_data_point)
print("Predicted probabilities for each class:", predicted_probabilities)
# iii. Report on the score for the SVM, what does the score measure?
y_pred = svm_model.predict(X_test)  
score = accuracy_score(y_test, y_pred)  
print("Accuracy score of the Support Vector Classifier model:", score)

Predicted probabilities for each class: [[0.00670553 0.90955909 0.08373537]]
Accuracy score of the Support Vector Classifier model: 1.0


In this case, the accuracy score is 1. This means all the samples in the test set were classified correctly!

# Part 5: Neural Network

In [6]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
mlp_model = MLPClassifier(max_iter=1000, random_state=42)  
mlp_model.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample_data_point = X_test.iloc[[0]]  
predicted_probabilities = mlp_model.predict_proba(sample_data_point)
print("Predicted probabilities for each class:", predicted_probabilities)
# iii. Report on the score for the Neural Network, what does the score measure?
y_pred = mlp_model.predict(X_test)  # Predict labels for the test set
score = accuracy_score(y_test, y_pred)
print("Accuracy score of the Neural Network model:", score)
# iv: Experiment with different options for the neural network, report on your best configuration
best_score = 0
best_params = {}

for hidden_layers in [(5,), (10,), (5, 5), (10, 10), (5, 10)]:
    for activation in ['identity', 'logistic', 'tanh', 'relu']:
        model = MLPClassifier(hidden_layer_sizes=hidden_layers, 
                              activation=activation, 
                              max_iter=1000, 
                              random_state=42)
        model.fit(X_train, y_train)
        score = model.score(X_test, y_test)

        print(f"Testing configuration - Hidden layers: {hidden_layers}, Activation: {activation}")
        print("Accuracy score:", score)
        if score > best_score:
            best_score = score
            best_params = {'hidden_layers': hidden_layers, 'activation': activation}

print("Best Configuration:")
print("Hidden layers:", best_params['hidden_layers'])
print("Activation function:", best_params['activation'])
print("Best accuracy score:", best_score)

Predicted probabilities for each class: [[5.79308270e-04 9.66003085e-01 3.34176064e-02]]
Accuracy score of the Neural Network model: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5,), Activation: identity
Accuracy score: 0.8


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5,), Activation: logistic
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5,), Activation: tanh
Accuracy score: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5,), Activation: relu
Accuracy score: 0.7333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (10,), Activation: identity
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (10,), Activation: logistic
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (10,), Activation: tanh
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (10,), Activation: relu
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 5), Activation: identity
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 5), Activation: logistic
Accuracy score: 0.7333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 5), Activation: tanh
Accuracy score: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 5), Activation: relu
Accuracy score: 0.7333333333333333
Testing configuration - Hidden layers: (10, 10), Activation: identity
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (10, 10), Activation: logistic
Accuracy score: 0.9333333333333333
Testing configuration - Hidden layers: (10, 10), Activation: tanh
Accuracy score: 0.9333333333333333
Testing configuration - Hidden layers: (10, 10), Activation: relu
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 10), Activation: identity
Accuracy score: 0.8


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 10), Activation: logistic
Accuracy score: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


Testing configuration - Hidden layers: (5, 10), Activation: tanh
Accuracy score: 1.0
Testing configuration - Hidden layers: (5, 10), Activation: relu
Accuracy score: 0.8666666666666667
Best Configuration:
Hidden layers: (5,)
Activation function: tanh
Best accuracy score: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(


The probabilities recieved seem reasonable, given that this dataset is well separated in feature space. The accuracy score of 1.0 means that the model perfectly classified all instances in the test set. Given that the Iris dataset is relatively small, simple, and clean, achieving perfect accuracy does not seem unusual. The warnings indicating that the maximum number of iterations was reached without convergence. It suggests fine-tuning may be needed. 

The best configuration :
Testing configuration - Hidden layers: (5, 5), Activation: tanh
Accuracy score: 1.0

# Part 6: K-Nearest Neighbors

In [8]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
knn_model = KNeighborsClassifier(n_neighbors=3)  
knn_model.fit(X_train, y_train)
# ii. For a sample datapoint, predict the probabilities for each possible class
sample_data_point = X_test.iloc[[0]] 
predicted_probabilities = knn_model.predict_proba(sample_data_point)
print("Predicted probabilities for each class:", predicted_probabilities)
# iii. Report on the score for kNN, what does the score measure?
y_pred = knn_model.predict(X_test)
score = accuracy_score(y_test, y_pred) 
print("Accuracy score of the k-Neighbors Classifier model:", score)

Predicted probabilities for each class: [[0. 1. 0.]]
Accuracy score of the k-Neighbors Classifier model: 1.0


The accuracy score measures the proportion of correctly classified samples in the test set.

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

All four models achieved perfect accuracy on this dataset. This makes it difficult to definitively identify a single "best" model. However, here are some factors to consider:
- Logistic regression works well with linearly separable data, which is the case for the Iris dataset.
- The kNN model predicted a full probability for one of the classes, although instances of other classes do exist. 
- Logistic regression straightforward and efficient, requiring less computational power compared to more complex models like neural networks or SVM. 

At first, accuracy scores of 1 were surprising to me. However, after considering how small and clean the dataset is, the score made sense. 