https://github.com/<redacted>/assignment-5-judging-flowers-<redacted>/blob/main/flowers_sample_notebook.ipynb 
<redacted>
cfc41b1


In [26]:
# Imports and pip installations (if needed)
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier



# Part 1: Load the dataset

In [4]:
# Load the dataset (load remotely or locally)

# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)
df = pd.read_csv('iris.csv')

print("First 15 rows of the dataset:")
print(df.head(15))

# Display a summary of the table information
print("\nSummary of the dataset:")
print(df.info())

First 15 rows of the dataset:
    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.1  se

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

The dataset consists of 150 entries (rows) and 5 columns (features), which can be described as follows:
Features:
sepal_length: The length of the sepal of the flower, measured in centimeters (float).
sepal_width: The width of the sepal, measured in centimeters (float).
petal_length: The length of the petal, measured in centimeters (float).
petal_width: The width of the petal, measured in centimeters (float).

Based on the different features, we can clasify it into catagories, Species which is the label. 
Setosa is a type of flower which typically represented by a specific set of measurements. 
We are doing this based on the measurement of size of petals and sepals. 


# Part 2: Split the dataset into train and test

In [6]:
# Take the dataset and split it into our features (X) and label (y)

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
# Split the dataset into features (X) and label (y)
X = df.drop(columns=['species'])  # Features: all columns except 'species'
y = df['species']  # Label: the 'species' column

# Use sklearn to split the features and labels into a training/test set (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Output the dimensions of the splits to verify
print(f'Training set size: {X_train.shape[0]} samples')
print(f'Test set size: {X_test.shape[0]} samples')


Training set size: 135 samples
Test set size: 15 samples


# Part 3: Logistic Regression

In [11]:
# i. Use sklearn to train a LogisticRegression model on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for Logistic regression model, what does the score measure?

# iv. Extract the coefficents and intercepts for the boundary line(s)

# i. Train a Logistic Regression model on the training set
model = LogisticRegression(multi_class='auto', solver='lbfgs', max_iter=200)
model.fit(X_train, y_train)

# ii. Predict the probabilities for a sample datapoint
sample_datapoint = X_test.iloc[12].values.reshape(1, -1)  # Get the 13th row of the test set as a sample
probabilities = model.predict_proba(sample_datapoint)

# iii. Report on the score for the Logistic Regression model
y_pred = model.predict(X_test)  # Make predictions on the test set
score = accuracy_score(y_test, y_pred)  # Calculate accuracy score
print(sample_datapoint)

print(f'Predicted probabilities for the sample data point: {probabilities}')
print(f'Accuracy score of the Logistic Regression model: {score}')

# iv. Extract the coefficients and intercepts for the boundary line(s)
coefficients = model.coef_  # Coefficients for each class
intercept = model.intercept_  # Intercepts for each class

print('Coefficients for each class:')
print(coefficients)
print('Intercepts for each class:')
print(intercept)

[[5.5 3.5 1.3 0.2]]
Predicted probabilities for the sample data point: [[9.75588815e-01 2.44111678e-02 1.69259234e-08]]
Accuracy score of the Logistic Regression model: 1.0
Coefficients for each class:
[[-0.42612585  0.96865398 -2.44812859 -1.03769847]
 [ 0.51149531 -0.21830267 -0.21574601 -0.8425377 ]
 [-0.08536945 -0.75035131  2.6638746   1.88023617]]
Intercepts for each class:
[  9.52941208   1.897714   -11.42712608]


/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


- Predictions on the test set are made using `model.predict(X_test)`.
- The accuracy score is calculated as the ratio of correctly predicted samples to the total number of samples in the test set using `accuracy_score(y_test, y_pred)`. Over here, since we have a score of 1, all the predictions were correct. For all the predictions and classification, the first one is setosa, second is vesicolor and third is virginica. this shows the intercepts for each class. 

# Part 4: Support Vector Machine

In [15]:
# i. Use sklearn to train a Support Vector Classifier on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for the SVM, what does the score measure?
X_train_svm, X_test_svm, y_train_svm, y_test_svm = train_test_split(X, y, test_size=0.1, random_state=42)

# i. Train a Support Vector Classifier on the training set
model = SVC(probability=True, random_state=42)  # Enable probability estimates
model.fit(X_train_svm, y_train_svm)

# ii. Predict the probabilities for a sample datapoint
sample_datapoint = X_test_svm.iloc[12].values.reshape(1, -1)  # Get the 13th row of the test set as a sample
probabilities = model.predict_proba(sample_datapoint)

# iii. Report on the score for the SVM
y_pred = model.predict(X_test_svm)  # Make predictions on the test set
score = accuracy_score(y_test_svm, y_pred)  # Calculate accuracy score

print(f'Predicted probabilities for the sample data point: {probabilities}')
print(f'Accuracy score of the Support Vector Classifier: {score}')

Predicted probabilities for the sample data point: [[0.97392896 0.0162471  0.00982394]]
Accuracy score of the Support Vector Classifier: 1.0


/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


The accuracy score ranges from 0.0 to 1.0, where:
1.0 indicates perfect classification (all instances correctly predicted).
0.0 indicates that none of the instances have been predicted correctly.
In practice, the accuracy score is a straightforward measure of model performance. Over here, the SVC shows that the model is accurate, showing that it predicts correctly 100% of the time. It also says that there is a 97% probability that the flower is setosa which is the correct prediction. 

# Part 5: Neural Network

In [44]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for the Neural Network, what does the score measure?

# iv: Experiment with different options for the neural network, report on your best configuration

# Split into training and testing sets (90% train, 10% test)
X_train_nn, X_test_nn, y_train_nn, y_test_nn = train_test_split(X, y, test_size=0.1, random_state=42)

# i. Train a Neural Network (MLP Classifier) on the training set
# You can modify 'hidden_layer_sizes', 'activation', 'solver', etc. as part of the experimentation.
model = MLPClassifier(hidden_layer_sizes=(50, 30), activation='relu', solver='adam', max_iter=400, random_state=42)
model.fit(X_train_nn, y_train_nn)

# ii. Predict the probabilities for a sample datapoint
sample_datapoint = X_test_nn.iloc[0].values.reshape(1, -1)  # Get the first row of the test set as a sample
probabilities = model.predict_proba(sample_datapoint)

# iii. Report on the score for the Neural Network
y_pred = model.predict(X_test_nn)  # Make predictions on the test set
score = accuracy_score(y_test_nn, y_pred)  # Calculate accuracy score

print(f'Predicted probabilities for the sample data point: {probabilities}')
print(f'Accuracy score of the Neural Network (MLP Classifier): {score}')

# iv: Experiment with different options for the neural network
# Trying different configurations
best_score = 0
best_config = {}
configs = [
    {'hidden_layer_sizes': (50,), 'activation': 'relu', 'max_iter': 100},
    {'hidden_layer_sizes': (60,), 'activation': 'tanh', 'max_iter': 200},
    {'hidden_layer_sizes': (50, 50), 'activation': 'logistic', 'max_iter': 400},
    {'hidden_layer_sizes': (30, 30, 30), 'activation': 'relu', 'max_iter': 100},
    {'hidden_layer_sizes': (100, 50), 'activation': 'relu', 'max_iter': 80}
]

for config in configs:
    model = MLPClassifier(hidden_layer_sizes=config['hidden_layer_sizes'], 
                          activation=config['activation'], 
                          max_iter=config['max_iter'], 
                          random_state=42)
    
    model.fit(X_train_nn, y_train_nn)
    y_pred = model.predict(X_test_nn)
    score = accuracy_score(y_test_nn, y_pred)
    print(f'Score{score}')
    print(f'config{config}')
    if score > best_score:
        best_score = score
        best_config = config

print(f'Best configuration: {best_config}')
print(f'Best accuracy score: {best_score}')

/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(
/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


Predicted probabilities for the sample data point: [[8.43945690e-04 9.71718525e-01 2.74375292e-02]]
Accuracy score of the Neural Network (MLP Classifier): 1.0
Score0.7333333333333333
config{'hidden_layer_sizes': (50,), 'activation': 'relu', 'max_iter': 100}
Score1.0
config{'hidden_layer_sizes': (60,), 'activation': 'tanh', 'max_iter': 200}
Score1.0
config{'hidden_layer_sizes': (50, 50), 'activation': 'logistic', 'max_iter': 400}
Score0.9333333333333333
config{'hidden_layer_sizes': (30, 30, 30), 'activation': 'relu', 'max_iter': 100}
Score1.0
config{'hidden_layer_sizes': (100, 50), 'activation': 'relu', 'max_iter': 80}
Best configuration: {'hidden_layer_sizes': (60,), 'activation': 'tanh', 'max_iter': 200}
Best accuracy score: 1.0


/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (400) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (80) reached and the optimization hasn't converged yet.
  warnings.warn(


I tried multiple different combinations of hidden layer sizes, neural netwoks and the amount of times back propogation is allowed. From what I saw, sigmoid which is logistic did not work very well. Relu worked well however only with many hidden layers and back propogation. I belive that tan worked best, with minimal layers and lesser back propogation, giving accuracy scores of 1.0

# Part 6: K-Nearest Neighbors

In [45]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier

# ii. For a sample datapoint, predict the probabilities for each possible class

# iii. Report on the score for kNN, what does the score measure?

X_train_kn, X_test_kn, y_train_kn, y_test_kn = train_test_split(X, y, test_size=0.1, random_state=42)

# i. Train a k-Neighbors Classifier (Note: this will load the data into the model)
model = KNeighborsClassifier(n_neighbors=3)  # Using 6 neighbors
model.fit(X_train_kn, y_train_kn)  # Fit loads the training data

# ii. Predict the probabilities for a sample datapoint
sample_datapoint = X_test_kn.iloc[0].values.reshape(1, -1)  # Get the first row of the test set as a sample
probabilities = model.predict_proba(sample_datapoint)

# iii. Report on the score for k-NN
y_pred = model.predict(X_test_kn)  # Make predictions on the test set
score = accuracy_score(y_test_kn, y_pred)  # Calculate accuracy score
print(sample_datapoint)
print(f'Predicted probabilities for the sample data point: {probabilities}')
print(f'Accuracy score of the k-NN Classifier: {score}')

[[6.1 2.8 4.7 1.2]]
Predicted probabilities for the sample data point: [[0. 1. 0.]]
Accuracy score of the k-NN Classifier: 1.0


/Users/<redacted>/Desktop/Temporary desktop/CS 383/Project 5/assignment-5-judging-flowers-<redacted>/.venv/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


The accuracy score is a measure of how well the model correctly predicts the labels for the test dataset. It ranges from 0.0 to 1.0:
1.0 means every prediction is correct.
0.0 means none of the predictions are correct.

I tried different neighbor sizes, and found that 3 was one of the numbers  that gave it an accuracy score of 1.0

# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

Logistic Regression:
- The Logistic Regression model typically produced solid accuracy scores. This model is relatively simple and interprets linear relationships among features well, making it effective for this dataset which has clear separability.
Support Vector Classifier (SVC):
- SVCs generally performed well, especially since it managed multi-class classification problems by creating decision boundaries in high-dimensional spaces. 
Neural Network (MLP Classifier):
- The MLP Classifier’s performance varied depending on the configuration (e.g., number of hidden layers, activation functions). While it has the potential to capture complex patterns due to its ability to learn non-linear decision boundaries, it may be more sensitive to overfitting, especially with small datasets like Iris.
k-Nearest Neighbors (k-NN):
- The k-NN model does not "learn" in the traditional sense but stores training data points. Its performance heavily depends on the choice of `k` (number of neighbors) and the distance metric used. The accuracy may not be as high on more complex or high-dimensional datasets, but it can be competitive on simple, well-separated datasets like Iris.

I think k-Nearest Neighbors worked best, because the dimensions of each category for a particular flower are clustered together, which makes it a good model to use. Since it is also not trained in the traditional sense, we could easily add more categories of flowers if wanted. 