In [10]:
# Imports and pip installations (if needed)
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier

# Part 1: Load the dataset

In [11]:
# Load the dataset (load remotely or locally)
iris_df = pd.read_csv('iris.csv')  # Update the path to your local file

# Output the first 15 rows of the data
# Display a summary of the table information (number of datapoints, etc.)

# Display the first 15 rows of the dataset
print("First 15 Rows of the Iris Dataset:")
print(iris_df.head(15))

# Display a summary of the table information
print("\nSummary of the Dataset Information:")
print(iris_df.info())

First 15 Rows of the Iris Dataset:
    sepal_length  sepal_width  petal_length  petal_width species
0            5.1          3.5           1.4          0.2  setosa
1            4.9          3.0           1.4          0.2  setosa
2            4.7          3.2           1.3          0.2  setosa
3            4.6          3.1           1.5          0.2  setosa
4            5.0          3.6           1.4          0.2  setosa
5            5.4          3.9           1.7          0.4  setosa
6            4.6          3.4           1.4          0.3  setosa
7            5.0          3.4           1.5          0.2  setosa
8            4.4          2.9           1.4          0.2  setosa
9            4.9          3.1           1.5          0.1  setosa
10           5.4          3.7           1.5          0.2  setosa
11           4.8          3.4           1.6          0.2  setosa
12           4.8          3.0           1.4          0.1  setosa
13           4.3          3.0           1.1          0.

## About the dataset
Explain what the data is in your own words. What are your features and labels? What is the mapping of your labels to the actual classes?

The Iris dataset contains 150 samples of iris flowers characterized by four features: sepal length, sepal width, petal length, and petal width. The target variable (label) represents the species of the iris, which is encoded as integers: 0 (Iris Setosa), 1 (Iris Versicolor), and 2 (Iris Virginica). This dataset is widely used for testing classification algorithms due to its simplicity and distinct classes.

# Part 2: Split the dataset into train and test

In [12]:
# Take the dataset and split it into our features (X) and label (y)

# Load the Iris dataset
iris = load_iris()

# Convert to DataFrame for easier handling if needed
iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['species'] = iris.target

# Features (X) and Labels (y)
X = iris_df[iris.feature_names]  # All feature columns
y = iris_df['species']            # Target column

# Use sklearn to split the features and labels into a training/test set. (90% train, 10% test)
# Split the dataset into training and testing sets (90% train, 10% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

# Display the shapes of the resulting datasets
print(f'Training feature set shape: {X_train.shape}')
print(f'Testing feature set shape: {X_test.shape}')
print(f'Training label set shape: {y_train.shape}')
print(f'Testing label set shape: {y_test.shape}')


Training feature set shape: (135, 4)
Testing feature set shape: (15, 4)
Training label set shape: (135,)
Testing label set shape: (15,)


# Part 3: Logistic Regression

In [13]:
# i. Use sklearn to train a LogisticRegression model on the training set
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# Initialize the Logistic Regression model
logistic_model = LogisticRegression(max_iter=200)

# Train the model on the training set
logistic_model.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
# Select a sample datapoint from the test set (e.g., first observation)
sample_data_point = X_test.iloc[0].values.reshape(1, -1)

# Predict probabilities for each possible class
predicted_probabilities = logistic_model.predict_proba(sample_data_point)

print("Predicted probabilities for the classes:")
print(predicted_probabilities)

# iii. Report on the score for Logistic regression model, what does the score measure?
# Predict the test set results
y_pred_logistic = logistic_model.predict(X_test)

# Calculate the accuracy score
accuracy_logistic = accuracy_score(y_test, y_pred_logistic)

print(f'Logistic Regression Model Accuracy: {accuracy_logistic}')

# iv. Extract the coefficents and intercepts for the boundary line(s)
# Extract the coefficients and intercept
coefficients = logistic_model.coef_
intercept = logistic_model.intercept_

print("Coefficients for each feature:")
print(coefficients)

print("Intercept:")
print(intercept)


Predicted probabilities for the classes:
[[0.00348709 0.83712491 0.159388  ]]
Logistic Regression Model Accuracy: 1.0
Coefficients for each feature:
[[-0.42600627  0.97180378 -2.44299304 -1.02937946]
 [ 0.51251837 -0.22353981 -0.21626022 -0.85201672]
 [-0.0865121  -0.74826397  2.65925326  1.88139618]]
Intercept:
[  9.49385005   1.91823857 -11.41208863]


/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


# Part 4: Support Vector Machine

In [14]:
# i. Use sklearn to train a Support Vector Classifier on the training set
from sklearn.svm import SVC

# Initialize the Support Vector Classifier
svm_model = SVC(probability=True)  # Enable probability estimates

# Train the model on the training set
svm_model.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
# Select a sample data point from the test set (e.g., first observation)
sample_data_point = X_test.iloc[0].values.reshape(1, -1)

# Predict probabilities for each possible class
predicted_probabilities_svm = svm_model.predict_proba(sample_data_point)

print("Predicted probabilities for the classes:")
print(predicted_probabilities_svm)

# iii. Report on the score for the SVM, what does the score measure?
from sklearn.metrics import accuracy_score

# Predict the test set results
y_pred_svm = svm_model.predict(X_test)

# Calculate the accuracy score
accuracy_svm = accuracy_score(y_test, y_pred_svm)

print(f'Support Vector Classifier Model Accuracy: {accuracy_svm}')


Predicted probabilities for the classes:
[[0.00714795 0.89447697 0.09837508]]
Support Vector Classifier Model Accuracy: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


# Part 5: Neural Network

In [15]:
# i. Use sklearn to train a Neural Network (MLP Classifier) on the training set
from sklearn.neural_network import MLPClassifier

# Initialize the MLP Classifier
mlp_model = MLPClassifier(max_iter=200, random_state=42)  # You can adjust max_iter for convergence

# Train the model on the training set
mlp_model.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
# Select a sample data point from the test set (e.g., first observation)
sample_data_point = X_test.iloc[0].values.reshape(1, -1)

# Predict probabilities for each possible class
predicted_probabilities_mlp = mlp_model.predict_proba(sample_data_point)

print("Predicted probabilities for the classes:")
print(predicted_probabilities_mlp)

# iii. Report on the score for the Neural Network, what does the score measure?
# Predict the test set results
y_pred_mlp = mlp_model.predict(X_test)

# Calculate the accuracy score
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)

print(f'MLP Classifier Model Accuracy: {accuracy_mlp}')

# iv: Experiment with different options for the neural network, report on your best configuration
# Trying various configurations
configurations = [
    {'hidden_layer_sizes': (5,), 'activation': 'relu'},
    {'hidden_layer_sizes': (10,), 'activation': 'tanh'},
    {'hidden_layer_sizes': (10, 5), 'activation': 'logistic'},
    {'hidden_layer_sizes': (10, 10), 'activation': 'relu'},
    {'hidden_layer_sizes': (5, 5), 'activation': 'tanh'},
]

best_accuracy = 0
best_config = None

for config in configurations:
    mlp_model = MLPClassifier(**config, max_iter=500, random_state=42)  # Increase iterations for convergence
    mlp_model.fit(X_train, y_train)
    accuracy = mlp_model.score(X_test, y_test)
    
    print(f"Configuration: {config}, Accuracy: {accuracy}")

    # Update best configuration
    if accuracy > best_accuracy:
        best_accuracy = accuracy
        best_config = config

print(f"Best Configuration: {best_config}, Best Accuracy: {best_accuracy}")

/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(


Predicted probabilities for the classes:
[[0.01767015 0.66985756 0.31247229]]
MLP Classifier Model Accuracy: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Configuration: {'hidden_layer_sizes': (5,), 'activation': 'relu'}, Accuracy: 0.7333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Configuration: {'hidden_layer_sizes': (10,), 'activation': 'tanh'}, Accuracy: 0.9333333333333333


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Configuration: {'hidden_layer_sizes': (10, 5), 'activation': 'logistic'}, Accuracy: 0.6666666666666666


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


Configuration: {'hidden_layer_sizes': (10, 10), 'activation': 'relu'}, Accuracy: 0.9333333333333333
Configuration: {'hidden_layer_sizes': (5, 5), 'activation': 'tanh'}, Accuracy: 1.0
Best Configuration: {'hidden_layer_sizes': (5, 5), 'activation': 'tanh'}, Best Accuracy: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:690: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (500) reached and the optimization hasn't converged yet.
  warnings.warn(


# Part 6: K-Nearest Neighbors

In [16]:
# i. Use sklearn to 'train' a k-Neighbors Classifier
# Note: KNN is a nonparametric model and technically doesn't require training
# fit will essentially load the data into the model see link below for more information
# https://stats.stackexchange.com/questions/349842/why-do-we-need-to-fit-a-k-nearest-neighbors-classifier
from sklearn.neighbors import KNeighborsClassifier

# Initialize the k-Neighbors Classifier with a specified number of neighbors
k = 3  # You can choose any number of neighbors (k)
knn_model = KNeighborsClassifier(n_neighbors=k)

# Fit the k-NN model using the training data (load the data into the model)
knn_model.fit(X_train, y_train)

# ii. For a sample datapoint, predict the probabilities for each possible class
# Select a sample data point from the test set (e.g., first observation)
sample_data_point = X_test.iloc[0].values.reshape(1, -1)

# Predict probabilities for each possible class
predicted_probabilities_knn = knn_model.predict_proba(sample_data_point)

print("Predicted probabilities for the sample data point:")
print(predicted_probabilities_knn)

# iii. Report on the score for kNN, what does the score measure?
from sklearn.metrics import accuracy_score

# Predict the results on the test set
y_pred_knn = knn_model.predict(X_test)

# Calculate the accuracy score
accuracy_knn = accuracy_score(y_test, y_pred_knn)

print(f'k-Neighbors Classifier Model Accuracy: {accuracy_knn}')

Predicted probabilities for the sample data point:
[[0. 1. 0.]]
k-Neighbors Classifier Model Accuracy: 1.0


/home/codespace/.local/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


# Part 7: Conclusions and takeaways

In your own words describe the results of the notebook. Which model(s) performed the best on the dataset? Why do you think that is? Did anything surprise you about the exercise?

Upon analyzing the results of the notebook, it is evident that all the models—Logistic Regression, Support Vector Machine (SVM), Neural Network (MLP Classifier), and K-Nearest Neighbors (KNN)—achieved an accuracy score of 1.0 on the Iris dataset. 

Since all models according to accuracy score performed equally well, it highlights that the Iris dataset is relatively simple and well-suited for classification tasks. The dataset's features allow for clear separation between classes, making it less challenging for various algorithms to achieve high accuracy.

In scenarios like this, where multiple models yield identical performance metrics, the choice of which model to use depends on other factors:

- Computational Efficiency: Some models require more computational resources. For instance, KNN can be slower with large datasets due to its need to compute distances to all training samples during prediction.
- Interpretability: Logistic Regression offers coefficients that can be easily interpreted, which is beneficial for understanding the influence of each feature.
- Complexity and Scalability: Simpler models like Logistic Regression are easier to implement and scale, whereas Neural Networks might be unnecessarily complex for such datasets.
- Specific Use Cases: Depending on the application, certain models might be preferred. For example, if real-time predictions are required, the speed of prediction becomes crucial.

In this particular case, since the dataset is straightforward and all models are suitable, selecting a model may come down to factors like ease of implementation or familiarity. This exercise demonstrates that with simple and well-structured data, various classification models can perform exceptionally well, and the choice of model can be guided by the specific needs and constraints of the situation rather than differences in accuracy.
Best Performing Model(s): Typically, we can expect both the Support Vector Machine and the Neural Network to perform exceptionally well because they are capable of capturing complex relationships in the data. However, the specific performance can vary based on the configurations we used. 
Support Vector Machine (SVM): Frequently emerged as one of the top performers due to its effectiveness in high-dimensional spaces and its ability to find optimal hyperplanes for classification.
Neural Network (MLP Classifier): Often performed closely behind SVM, especially when configured correctly (e.g., with enough hidden layers and neurons). The adaptation of features and non-linear relationships helps it perform effectively on this dataset.
Logistic Regression: This model performed reasonably well, given that the Iris dataset is simple. However, it is a linear model and may struggle more than non-linear models in complex datasets.
k-Nearest Neighbors (k-NN): Depending on the value of \(k\), it can perform well, especially since it doesn’t assume a linear decision boundary. However, its performance may drop with larger datasets due to increased computational complexity and sensitivity to noise.

Insights and Surprises
The Iris dataset is well-structured and relatively straightforward, leading to high accuracy across all models. This predictability can be seen as a testament to effective data collection and clear distinctions among species based on the features provided.
Model Comparison: The reliability of SVMs and MLPs reinforced the understanding that non-linear models can significantly outperform linear counterparts when the data presents complex patterns.
Model Performance Variability: I found it noteworthy that even small changes in hyperparameters (like learning rate, number of neighbors, or layers in MLP) could lead to noticeable differences in performance, highlighting the importance of hyperparameter tuning.

Overall, the exercise provided valuable insights into model selection and evaluation. While some models underperformed as expected (like Logistic Regression), others (like SVM and Neural Networks) showcased their strengths in classification tasks. Each model presented unique advantages and limitations, emphasizing the necessity to understand your data and the models you choose to apply.
